name: "🐛 Bug Report"
description: Report a bug
title: "[BUG] "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

    - type: input
      id: library-version
      attributes:
          label: Library Version
          description: What is the library version?
      validations:
          required: true

    - type: input
      id: python-version
      attributes:
          label: Python Version
          description: Run `python --version` to get your version
      validations:
          required: true

    - type: dropdown
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you using?
          options:
              - Windows
              - macOS
              - Linux
      validations:
          required: true

    - type: dropdown
      id: auth-method
      attributes:
          label: Authentication Method
          description: How are you authenticating?
          options:
              - Azure CLI (az login)
              - Service principal (secret)
              - Service principal (certificate)
              - Service principal (federated credential)
              - Managed identity
              - Other
      validations:
          required: true

    - type: textarea
      id: problem-description
      attributes:
          label: What is the problem?
          description: Describe the bug you encountered and what the gap is.
      validations:
          required: true

    - type: textarea
      id: reproduction-steps
      attributes:
          label: Steps to reproduce
          description: Please provide step-by-step instructions to reproduce the bug
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: What did you expect to happen?
      validations:
          required: true

    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual behavior
          description: What actually happened? Include error messages if applicable.
      validations:
          required: true

    - type: textarea
      id: solution-description
      attributes:
          label: Is there an ideal solution?
          description: Describe the ideal solution if there is one.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context, screenshots, logs, error output, etc
          description: Add any other relevant details like specific workspace/item types involved, related issues or documentation, API request IDs. If it is long, please paste to https://gist.github.com/ and insert the link here. Ensure to strip any non public information.
      validations:
          required: false
