name: "🤖 GitHub Copilot Assignment"
description: Issue template for tasks assigned to GitHub Copilot Agent
title: "[COPILOT] "
labels: ["copilot"]
body:
    - type: markdown
      attributes:
          value: Used internally to raise issues specifically for GitHub Copilot agent assistance. Provide as much context as possible to help the agent work efficiently.

    - type: dropdown
      id: task-type
      attributes:
          label: Task Type
          description: What kind of work is this?
          options:
              - Bug fix
              - New feature
              - Refactoring
              - Documentation
              - Tests
              - Other
      validations:
          required: true

    - type: textarea
      id: task-description
      attributes:
          label: Task Description
          description: Describe what needs to be done and any relevant context.
          placeholder: |
              What needs to be done:
              Context/Background:
              Error message (if applicable):
      validations:
          required: true

    - type: textarea
      id: affected-components
      attributes:
          label: Affected Files/Components
          description: List specific files, modules, or components involved.
          placeholder: |
              src/fabric_cicd/fabric_workspace.py
              tests/test_fabric_workspace.py
      validations:
          required: false

    - type: textarea
      id: reproduction-steps
      attributes:
          label: Reproduction Steps
          description: Steps to reproduce the issue (for bugs).
          placeholder: |
              1. Run `uv run pytest tests/test_example.py`
              2. Observe error...
      validations:
          required: false

    - type: textarea
      id: solution-description
      attributes:
          label: Proposed Solution
          description: Describe the ideal solution with specific technical details.
          placeholder: |
              Approach:
              Key changes needed:
              Considerations:
      validations:
          required: false

    - type: textarea
      id: success-criteria
      attributes:
          label: Success Criteria
          description: Define completion requirements. Remove items that don't apply.
          placeholder: |
              - All existing tests pass (`uv run pytest -v`)
              - New tests added for changes
              - `uv run ruff format` passes
              - `uv run ruff check` passes
              - Import test passes (`uv run python -c "from fabric_cicd import FabricWorkspace"`)
              - Documentation updated (if applicable)
              - PR title follows format: "Fixes #XXX - Description"
      validations:
          required: false

    - type: textarea
      id: scope-boundaries
      attributes:
          label: Scope & Boundaries
          description: What should NOT be changed or is out of scope?
          placeholder: |
              Do NOT modify:
              Out of scope:
      validations:
          required: false

    - type: textarea
      id: related-context
      attributes:
          label: Related Issues/PRs/Docs
          description: Links to related issues, PRs, or documentation.
          placeholder: |
              - Related to #123
              - See docs/example/usage.md
      validations:
          required: false
